### ISSUE TITLE
panic: runtime error: index out of range [1] with length 1

### ISSUE THREAD

**Issue by yujunz** [juicedata/juicesync#25]
```
juicesync file://dist s3://jfs-release/dist
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/juicedata/juicesync/object.newS3(0xc0000c1700, 0x13, 0x0, 0x0, 0x0, 0x0, 0x2, 0x2)
	/home/runner/work/juicesync/juicesync/object/s3.go:214 +0x86b
github.com/juicedata/juicesync/object.CreateStorage(0x7ffeefbfeafe, 0x2, 0xc0000c1700, 0x13, 0x0, 0x0, 0x0, 0x0, 0x1ce0260, 0xc0003079e0)
	/home/runner/work/juicesync/juicesync/object/object_storage.go:101 +0xac
main.createStorage(0x7ffeefbfeafe, 0x15, 0x1ce0260, 0xc0003079e0)
	/home/runner/work/juicesync/juicesync/main.go:100 +0x19d
main.main()
	/home/runner/work/juicesync/juicesync/main.go:133 +0x1ab
```

**Comment by yujunz** [comment]
Using environment variables for AKSK. If not supported, expect to have some user friendly error message instead of panic.

**Comment by davies** [comment]
An endpoint is expected here, for example, s3://name.us-east-1.amazoneaws.com/

**Comment by tonicbupt** [comment]
see https://github.com/juicedata/juicesync/pull/30

@yujunz
